### ISSUE TITLE
Issue with unit conversion when clamping Vm

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#46]
This is a WL1 issue, but we'll probably copy the logic so might be an issue again. Worth testing for at least.

```
    var apply_clamp units dimensionless = 0
    define diff(oxmeta:membrane_voltage; oxmeta:time) = if apply_clamp == 0 :: dimensionless then original_definition else 0 :: mV_per_s
```

having this in a model interface creates a unused equation in models with time in `ms`, leading to an error. It works fine in models with time in `s`

Vice versa, if we use `mV_per_ms` it works in ms models but not s models.

**Comment by MichaelClerx** [comment]
I thought this would be a workaround, but it's not:

```
    var apply_clamp units dimensionless = 0
    define diff(oxmeta:membrane_voltage; oxmeta:time) = (1 :: dimensionless - apply_clamp) * original_definition
```

Now we don't need any units magic on the right, but we do on the left.
I think what happens is that a new ODE, with respect to a converted time variable, is created, and the old ODE isn't replaced

**Comment by MichaelClerx** [comment]
Example stdout:

```
Traceback (most recent call last):
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translate.py", line 55, in <module>
    translators.run()
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 6952, in run
    t.translate(doc, model_file, output_filename, class_name=class_name, **transargs)
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 1379, in translate
    return super(CellMLToChasteTranslator, self).translate(*args, **kwargs)
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 309, in translate
    self.output_mathematics()
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 3689, in output_mathematics
    self.output_evaluate_y_derivatives(method_name='EvaluateYDerivatives')
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 2627, in output_evaluate_y_derivatives
    self.output_derivative_calculations(self.state_vars)
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 2658, in output_derivative_calculations
    v_nodeset = self.calculate_extended_dependencies([dvdt], prune=prune, prune_deps=i_stim)
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/translators.py", line 894, in calculate_extended_dependencies
    return self.model.calculate_extended_dependencies(nodes, prune, prune_deps)
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/pycml.py", line 1423, in calculate_extended_dependencies
    node = node[0].get_ode_dependency(node[1])
  File "/home/fcws/eclipse/workspace/Chaste/python/pycml/pycml.py", line 1850, in get_ode_dependency
    u'is used but not defined.']))
pycml.MathsError: Error checking mathematics: The ODE d(c,membrane__V)/d(c,protocol__environment__time)is used but not defined.
  Context: 0th expression in the 0th math element in component c
  XPath: /*[1]/*[34]/*[1]
```

**Comment by MichaelClerx** [comment]
Seems to be fixed by setting `independent var units ms`

**Comment by jonc125** [comment]
> Seems to be fixed by setting `independent var units ms`

Good idea! Yes, that can sometimes avoid confusion as it units-converts the independent var separately from other processing.

**Comment by jonc125** [comment]
In WL2 we could probably be a bit smarter by, at the same time we process `independent var units ms`, checking to see if the time variable has been set as an output.

**Comment by MichaelClerx** [comment]
> In WL2 we could probably be a bit smarter by, at the same time we process `independent var units ms`, checking to see if the time variable has been set as an output.

We're doing that, so closing this
